# Generated by Django 5.1.2 on 2024-10-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_recipe_created_at_recipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='secret',
            field=models.TextField(default='This is what i do differently'),
        ),
    ]
